name: Prank
version: 1.0
main: me.RacerMatt.prank.Prank
description: Simple prank plugin.

commands:
    fakeop:
        usage: /<command>
        description: Fake op a player
    fakejoin:
        usage: /<command>
        description: Have a user fake join the server